baseURL: "https://oudam.es/"
title: "Home"
paginate: 7
theme: "PaperMod"

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

minify:
  disableXML: true

menu:
  main:
    - name: Archive
      url: archives
      weight: 1
    - name: Tags
      url: tags/
      weight: 2
    - name: Categories
      url: categories/
      weight: 3

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Outdam Meas's Blog Production Params"
  author: Outdam Meas

  defaultTheme: auto
  #  disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true
  images: [ "cover.png" ]

  homeInfoParams:
    Title: "Outdam Meas's posts"
  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/outdam/"
  hideFooter: true
taxonomies:
  category: categories
  tag: tags
  series: series

services:
  twitter:
    disableInlineCSS: true